# Generated by Django 6.0.1 on 2026-01-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
